# Generated by Django 4.0.5 on 2022-06-23 16:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_passenger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
